// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  All SceMi types
// Generated on: Fri Apr 29 11:01:01 EDT 2016
// Bluespec version: 2014.07.A 2014-07-30 34078

#pragma once

#include "PowerStruct.h" 
#include "PowerAssoc.h" 
#include "Tuple2_UInt_24_UInt_24.h" 
#include "ProbeControl.h" 
#include "PrbNum.h" 
#include "CosimStruct.h" 
#include "Key_Iv.h" 
#include "PowerProbe.h" 
#include "PwPrbKind.h" 
#include "SimulationControlReq.h" 
#include "SimulationStatusResp.h" 
#include "Tag.h" 
#include "CreditCount.h" 
#include "KeyType.h" 
#include "BlockType.h" 
#include "Lag.h" 
#include "ClkNextRdy.h" 
