/*
 * Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
 * 
 * On Sat Mar 12 13:28:57 EST 2016
 * 
 */
#include "bluesim_primitives.h"
#include "mkCsrFile.h"


/* String declarations */
static std::string const __str_literal_1("\nCycle %d ----------------------------------------------------",
					 62u);


/* Constructor */
MOD_mkCsrFile::MOD_mkCsrFile(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_coreId(simHdl, "coreId", this, 32u, 0u, (tUInt8)0u),
    INST_cycles(simHdl, "cycles", this, 32u, 0u, (tUInt8)0u),
    INST_numInsts(simHdl, "numInsts", this, 32u, 0u, (tUInt8)0u),
    INST_startReg(simHdl, "startReg", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_toHostFifo_clearReq_ehrReg(simHdl,
				    "toHostFifo_clearReq_ehrReg",
				    this,
				    1u,
				    (tUInt8)0u,
				    (tUInt8)0u),
    INST_toHostFifo_clearReq_ignored_wires_0(simHdl,
					     "toHostFifo_clearReq_ignored_wires_0",
					     this,
					     1u,
					     (tUInt8)0u),
    INST_toHostFifo_clearReq_ignored_wires_1(simHdl,
					     "toHostFifo_clearReq_ignored_wires_1",
					     this,
					     1u,
					     (tUInt8)0u),
    INST_toHostFifo_clearReq_virtual_reg_0(simHdl,
					   "toHostFifo_clearReq_virtual_reg_0",
					   this,
					   1u,
					   (tUInt8)0u),
    INST_toHostFifo_clearReq_virtual_reg_1(simHdl,
					   "toHostFifo_clearReq_virtual_reg_1",
					   this,
					   1u,
					   (tUInt8)0u),
    INST_toHostFifo_clearReq_wires_0(simHdl, "toHostFifo_clearReq_wires_0", this, 1u, (tUInt8)0u),
    INST_toHostFifo_clearReq_wires_1(simHdl, "toHostFifo_clearReq_wires_1", this, 1u, (tUInt8)0u),
    INST_toHostFifo_data_0(simHdl, "toHostFifo_data_0", this, 18u),
    INST_toHostFifo_data_1(simHdl, "toHostFifo_data_1", this, 18u),
    INST_toHostFifo_deqP(simHdl, "toHostFifo_deqP", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_toHostFifo_deqReq_ehrReg(simHdl, "toHostFifo_deqReq_ehrReg", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_toHostFifo_deqReq_ignored_wires_0(simHdl,
					   "toHostFifo_deqReq_ignored_wires_0",
					   this,
					   1u,
					   (tUInt8)0u),
    INST_toHostFifo_deqReq_ignored_wires_1(simHdl,
					   "toHostFifo_deqReq_ignored_wires_1",
					   this,
					   1u,
					   (tUInt8)0u),
    INST_toHostFifo_deqReq_ignored_wires_2(simHdl,
					   "toHostFifo_deqReq_ignored_wires_2",
					   this,
					   1u,
					   (tUInt8)0u),
    INST_toHostFifo_deqReq_virtual_reg_0(simHdl,
					 "toHostFifo_deqReq_virtual_reg_0",
					 this,
					 1u,
					 (tUInt8)0u),
    INST_toHostFifo_deqReq_virtual_reg_1(simHdl,
					 "toHostFifo_deqReq_virtual_reg_1",
					 this,
					 1u,
					 (tUInt8)0u),
    INST_toHostFifo_deqReq_virtual_reg_2(simHdl,
					 "toHostFifo_deqReq_virtual_reg_2",
					 this,
					 1u,
					 (tUInt8)0u),
    INST_toHostFifo_deqReq_wires_0(simHdl, "toHostFifo_deqReq_wires_0", this, 1u, (tUInt8)0u),
    INST_toHostFifo_deqReq_wires_1(simHdl, "toHostFifo_deqReq_wires_1", this, 1u, (tUInt8)0u),
    INST_toHostFifo_deqReq_wires_2(simHdl, "toHostFifo_deqReq_wires_2", this, 1u, (tUInt8)0u),
    INST_toHostFifo_empty(simHdl, "toHostFifo_empty", this, 1u, (tUInt8)1u, (tUInt8)0u),
    INST_toHostFifo_enqP(simHdl, "toHostFifo_enqP", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_toHostFifo_enqReq_ehrReg(simHdl, "toHostFifo_enqReq_ehrReg", this, 19u, 174762u, (tUInt8)0u),
    INST_toHostFifo_enqReq_ignored_wires_0(simHdl,
					   "toHostFifo_enqReq_ignored_wires_0",
					   this,
					   19u,
					   (tUInt8)0u),
    INST_toHostFifo_enqReq_ignored_wires_1(simHdl,
					   "toHostFifo_enqReq_ignored_wires_1",
					   this,
					   19u,
					   (tUInt8)0u),
    INST_toHostFifo_enqReq_ignored_wires_2(simHdl,
					   "toHostFifo_enqReq_ignored_wires_2",
					   this,
					   19u,
					   (tUInt8)0u),
    INST_toHostFifo_enqReq_virtual_reg_0(simHdl,
					 "toHostFifo_enqReq_virtual_reg_0",
					 this,
					 1u,
					 (tUInt8)0u),
    INST_toHostFifo_enqReq_virtual_reg_1(simHdl,
					 "toHostFifo_enqReq_virtual_reg_1",
					 this,
					 1u,
					 (tUInt8)0u),
    INST_toHostFifo_enqReq_virtual_reg_2(simHdl,
					 "toHostFifo_enqReq_virtual_reg_2",
					 this,
					 1u,
					 (tUInt8)0u),
    INST_toHostFifo_enqReq_wires_0(simHdl, "toHostFifo_enqReq_wires_0", this, 19u, (tUInt8)0u),
    INST_toHostFifo_enqReq_wires_1(simHdl, "toHostFifo_enqReq_wires_1", this, 19u, (tUInt8)0u),
    INST_toHostFifo_enqReq_wires_2(simHdl, "toHostFifo_enqReq_wires_2", this, 19u, (tUInt8)0u),
    INST_toHostFifo_full(simHdl, "toHostFifo_full", this, 1u, (tUInt8)0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  PORT_EN_cpuToHost = false;
  PORT_EN_wr = false;
  PORT_EN_start = false;
  PORT_wr_idx = 0u;
  PORT_wr_val = 0u;
  PORT_start_id = 0u;
  PORT_rd_idx = 0u;
  PORT_cpuToHost = 0u;
  PORT_RDY_cpuToHost = false;
  PORT_RDY_wr = false;
  PORT_RDY_start = false;
  PORT_started = false;
  PORT_RDY_started = false;
  PORT_rd = 0u;
  PORT_RDY_rd = false;
  symbol_count = 77u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkCsrFile::init_symbols_0()
{
  init_symbol(&symbols[0u], "CAN_FIRE_cpuToHost", SYM_DEF, &DEF_CAN_FIRE_cpuToHost, 1u);
  init_symbol(&symbols[1u], "CAN_FIRE_RL_count", SYM_DEF, &DEF_CAN_FIRE_RL_count, 1u);
  init_symbol(&symbols[2u],
	      "CAN_FIRE_RL_toHostFifo_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_toHostFifo_canonicalize,
	      1u);
  init_symbol(&symbols[3u],
	      "CAN_FIRE_RL_toHostFifo_clearReq_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_toHostFifo_clearReq_canonicalize,
	      1u);
  init_symbol(&symbols[4u],
	      "CAN_FIRE_RL_toHostFifo_deqReq_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_toHostFifo_deqReq_canonicalize,
	      1u);
  init_symbol(&symbols[5u],
	      "CAN_FIRE_RL_toHostFifo_enqReq_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_toHostFifo_enqReq_canonicalize,
	      1u);
  init_symbol(&symbols[6u], "CAN_FIRE_rd", SYM_DEF, &DEF_CAN_FIRE_rd, 1u);
  init_symbol(&symbols[7u], "CAN_FIRE_start", SYM_DEF, &DEF_CAN_FIRE_start, 1u);
  init_symbol(&symbols[8u], "CAN_FIRE_started", SYM_DEF, &DEF_CAN_FIRE_started, 1u);
  init_symbol(&symbols[9u], "CAN_FIRE_wr", SYM_DEF, &DEF_CAN_FIRE_wr, 1u);
  init_symbol(&symbols[10u], "coreId", SYM_MODULE, &INST_coreId);
  init_symbol(&symbols[11u], "cpuToHost", SYM_PORT, &PORT_cpuToHost, 18u);
  init_symbol(&symbols[12u], "cycles", SYM_MODULE, &INST_cycles);
  init_symbol(&symbols[13u], "EN_cpuToHost", SYM_PORT, &PORT_EN_cpuToHost, 1u);
  init_symbol(&symbols[14u], "EN_start", SYM_PORT, &PORT_EN_start, 1u);
  init_symbol(&symbols[15u], "EN_wr", SYM_PORT, &PORT_EN_wr, 1u);
  init_symbol(&symbols[16u], "numInsts", SYM_MODULE, &INST_numInsts);
  init_symbol(&symbols[17u], "RDY_cpuToHost", SYM_PORT, &PORT_RDY_cpuToHost, 1u);
  init_symbol(&symbols[18u], "RDY_rd", SYM_PORT, &PORT_RDY_rd, 1u);
  init_symbol(&symbols[19u], "RDY_start", SYM_PORT, &PORT_RDY_start, 1u);
  init_symbol(&symbols[20u], "RDY_started", SYM_PORT, &PORT_RDY_started, 1u);
  init_symbol(&symbols[21u], "RDY_wr", SYM_PORT, &PORT_RDY_wr, 1u);
  init_symbol(&symbols[22u], "RL_count", SYM_RULE);
  init_symbol(&symbols[23u], "RL_toHostFifo_canonicalize", SYM_RULE);
  init_symbol(&symbols[24u], "RL_toHostFifo_clearReq_canonicalize", SYM_RULE);
  init_symbol(&symbols[25u], "RL_toHostFifo_deqReq_canonicalize", SYM_RULE);
  init_symbol(&symbols[26u], "RL_toHostFifo_enqReq_canonicalize", SYM_RULE);
  init_symbol(&symbols[27u], "rd", SYM_PORT, &PORT_rd, 32u);
  init_symbol(&symbols[28u], "rd_idx", SYM_PORT, &PORT_rd_idx, 12u);
  init_symbol(&symbols[29u], "start_id", SYM_PORT, &PORT_start_id, 32u);
  init_symbol(&symbols[30u], "started", SYM_PORT, &PORT_started, 1u);
  init_symbol(&symbols[31u], "startReg", SYM_MODULE, &INST_startReg);
  init_symbol(&symbols[32u],
	      "toHostFifo_clearReq_ehrReg",
	      SYM_MODULE,
	      &INST_toHostFifo_clearReq_ehrReg);
  init_symbol(&symbols[33u],
	      "toHostFifo_clearReq_ignored_wires_0",
	      SYM_MODULE,
	      &INST_toHostFifo_clearReq_ignored_wires_0);
  init_symbol(&symbols[34u],
	      "toHostFifo_clearReq_ignored_wires_1",
	      SYM_MODULE,
	      &INST_toHostFifo_clearReq_ignored_wires_1);
  init_symbol(&symbols[35u],
	      "toHostFifo_clearReq_virtual_reg_0",
	      SYM_MODULE,
	      &INST_toHostFifo_clearReq_virtual_reg_0);
  init_symbol(&symbols[36u],
	      "toHostFifo_clearReq_virtual_reg_1",
	      SYM_MODULE,
	      &INST_toHostFifo_clearReq_virtual_reg_1);
  init_symbol(&symbols[37u],
	      "toHostFifo_clearReq_wires_0",
	      SYM_MODULE,
	      &INST_toHostFifo_clearReq_wires_0);
  init_symbol(&symbols[38u],
	      "toHostFifo_clearReq_wires_1",
	      SYM_MODULE,
	      &INST_toHostFifo_clearReq_wires_1);
  init_symbol(&symbols[39u], "toHostFifo_data_0", SYM_MODULE, &INST_toHostFifo_data_0);
  init_symbol(&symbols[40u], "toHostFifo_data_1", SYM_MODULE, &INST_toHostFifo_data_1);
  init_symbol(&symbols[41u], "toHostFifo_deqP", SYM_MODULE, &INST_toHostFifo_deqP);
  init_symbol(&symbols[42u], "toHostFifo_deqReq_ehrReg", SYM_MODULE, &INST_toHostFifo_deqReq_ehrReg);
  init_symbol(&symbols[43u],
	      "toHostFifo_deqReq_ignored_wires_0",
	      SYM_MODULE,
	      &INST_toHostFifo_deqReq_ignored_wires_0);
  init_symbol(&symbols[44u],
	      "toHostFifo_deqReq_ignored_wires_1",
	      SYM_MODULE,
	      &INST_toHostFifo_deqReq_ignored_wires_1);
  init_symbol(&symbols[45u],
	      "toHostFifo_deqReq_ignored_wires_2",
	      SYM_MODULE,
	      &INST_toHostFifo_deqReq_ignored_wires_2);
  init_symbol(&symbols[46u],
	      "toHostFifo_deqReq_virtual_reg_0",
	      SYM_MODULE,
	      &INST_toHostFifo_deqReq_virtual_reg_0);
  init_symbol(&symbols[47u],
	      "toHostFifo_deqReq_virtual_reg_1",
	      SYM_MODULE,
	      &INST_toHostFifo_deqReq_virtual_reg_1);
  init_symbol(&symbols[48u],
	      "toHostFifo_deqReq_virtual_reg_2",
	      SYM_MODULE,
	      &INST_toHostFifo_deqReq_virtual_reg_2);
  init_symbol(&symbols[49u],
	      "toHostFifo_deqReq_wires_0",
	      SYM_MODULE,
	      &INST_toHostFifo_deqReq_wires_0);
  init_symbol(&symbols[50u],
	      "toHostFifo_deqReq_wires_1",
	      SYM_MODULE,
	      &INST_toHostFifo_deqReq_wires_1);
  init_symbol(&symbols[51u],
	      "toHostFifo_deqReq_wires_2",
	      SYM_MODULE,
	      &INST_toHostFifo_deqReq_wires_2);
  init_symbol(&symbols[52u], "toHostFifo_empty", SYM_MODULE, &INST_toHostFifo_empty);
  init_symbol(&symbols[53u], "toHostFifo_empty__h5796", SYM_DEF, &DEF_toHostFifo_empty__h5796, 1u);
  init_symbol(&symbols[54u], "toHostFifo_enqP", SYM_MODULE, &INST_toHostFifo_enqP);
  init_symbol(&symbols[55u], "toHostFifo_enqReq_ehrReg", SYM_MODULE, &INST_toHostFifo_enqReq_ehrReg);
  init_symbol(&symbols[56u],
	      "toHostFifo_enqReq_ignored_wires_0",
	      SYM_MODULE,
	      &INST_toHostFifo_enqReq_ignored_wires_0);
  init_symbol(&symbols[57u],
	      "toHostFifo_enqReq_ignored_wires_1",
	      SYM_MODULE,
	      &INST_toHostFifo_enqReq_ignored_wires_1);
  init_symbol(&symbols[58u],
	      "toHostFifo_enqReq_ignored_wires_2",
	      SYM_MODULE,
	      &INST_toHostFifo_enqReq_ignored_wires_2);
  init_symbol(&symbols[59u],
	      "toHostFifo_enqReq_virtual_reg_0",
	      SYM_MODULE,
	      &INST_toHostFifo_enqReq_virtual_reg_0);
  init_symbol(&symbols[60u],
	      "toHostFifo_enqReq_virtual_reg_1",
	      SYM_MODULE,
	      &INST_toHostFifo_enqReq_virtual_reg_1);
  init_symbol(&symbols[61u],
	      "toHostFifo_enqReq_virtual_reg_2",
	      SYM_MODULE,
	      &INST_toHostFifo_enqReq_virtual_reg_2);
  init_symbol(&symbols[62u],
	      "toHostFifo_enqReq_wires_0",
	      SYM_MODULE,
	      &INST_toHostFifo_enqReq_wires_0);
  init_symbol(&symbols[63u],
	      "toHostFifo_enqReq_wires_1",
	      SYM_MODULE,
	      &INST_toHostFifo_enqReq_wires_1);
  init_symbol(&symbols[64u],
	      "toHostFifo_enqReq_wires_2",
	      SYM_MODULE,
	      &INST_toHostFifo_enqReq_wires_2);
  init_symbol(&symbols[65u], "toHostFifo_full", SYM_MODULE, &INST_toHostFifo_full);
  init_symbol(&symbols[66u], "toHostFifo_full__h5764", SYM_DEF, &DEF_toHostFifo_full__h5764, 1u);
  init_symbol(&symbols[67u], "WILL_FIRE_cpuToHost", SYM_DEF, &DEF_WILL_FIRE_cpuToHost, 1u);
  init_symbol(&symbols[68u], "WILL_FIRE_RL_count", SYM_DEF, &DEF_WILL_FIRE_RL_count, 1u);
  init_symbol(&symbols[69u],
	      "WILL_FIRE_RL_toHostFifo_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_toHostFifo_canonicalize,
	      1u);
  init_symbol(&symbols[70u],
	      "WILL_FIRE_RL_toHostFifo_clearReq_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_toHostFifo_clearReq_canonicalize,
	      1u);
  init_symbol(&symbols[71u],
	      "WILL_FIRE_RL_toHostFifo_deqReq_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_toHostFifo_deqReq_canonicalize,
	      1u);
  init_symbol(&symbols[72u],
	      "WILL_FIRE_RL_toHostFifo_enqReq_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_toHostFifo_enqReq_canonicalize,
	      1u);
  init_symbol(&symbols[73u], "WILL_FIRE_start", SYM_DEF, &DEF_WILL_FIRE_start, 1u);
  init_symbol(&symbols[74u], "WILL_FIRE_wr", SYM_DEF, &DEF_WILL_FIRE_wr, 1u);
  init_symbol(&symbols[75u], "wr_idx", SYM_PORT, &PORT_wr_idx, 13u);
  init_symbol(&symbols[76u], "wr_val", SYM_PORT, &PORT_wr_val, 32u);
}


/* Rule actions */

void MOD_mkCsrFile::RL_toHostFifo_enqReq_canonicalize()
{
  tUInt32 DEF_IF_toHostFifo_enqReq_wires_2_whas_THEN_toHostF_ETC___d30;
  tUInt32 DEF_IF_toHostFifo_enqReq_wires_2_whas_THEN_toHostF_ETC___d28;
  tUInt8 DEF_toHostFifo_enqReq_wires_2_wget_BIT_18___d3;
  tUInt8 DEF_toHostFifo_enqReq_wires_2_whas____d1;
  tUInt32 DEF_toHostFifo_enqReq_wires_2_wget____d2;
  DEF_toHostFifo_enqReq_wires_2_wget____d2 = INST_toHostFifo_enqReq_wires_2.METH_wget();
  DEF_toHostFifo_enqReq_wires_1_wget____d5 = INST_toHostFifo_enqReq_wires_1.METH_wget();
  DEF_toHostFifo_enqReq_wires_0_wget____d8 = INST_toHostFifo_enqReq_wires_0.METH_wget();
  DEF_toHostFifo_enqReq_ehrReg___d10 = INST_toHostFifo_enqReq_ehrReg.METH_read();
  DEF_toHostFifo_enqReq_wires_2_whas____d1 = INST_toHostFifo_enqReq_wires_2.METH_whas();
  DEF_toHostFifo_enqReq_wires_1_whas____d4 = INST_toHostFifo_enqReq_wires_1.METH_whas();
  DEF_toHostFifo_enqReq_wires_0_whas____d7 = INST_toHostFifo_enqReq_wires_0.METH_whas();
  DEF_toHostFifo_enqReq_ehrReg_0_BITS_17_TO_0___d25 = (tUInt32)(262143u & DEF_toHostFifo_enqReq_ehrReg___d10);
  DEF_toHostFifo_enqReq_ehrReg_0_BIT_18___d11 = (tUInt8)(DEF_toHostFifo_enqReq_ehrReg___d10 >> 18u);
  DEF_toHostFifo_enqReq_wires_2_wget_BIT_18___d3 = (tUInt8)(DEF_toHostFifo_enqReq_wires_2_wget____d2 >> 18u);
  DEF_toHostFifo_enqReq_wires_0_wget_BIT_18___d9 = (tUInt8)(DEF_toHostFifo_enqReq_wires_0_wget____d8 >> 18u);
  DEF_toHostFifo_enqReq_wires_1_wget_BIT_18___d6 = (tUInt8)(DEF_toHostFifo_enqReq_wires_1_wget____d5 >> 18u);
  DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d13 = DEF_toHostFifo_enqReq_wires_1_whas____d4 ? DEF_toHostFifo_enqReq_wires_1_wget_BIT_18___d6 : (DEF_toHostFifo_enqReq_wires_0_whas____d7 ? DEF_toHostFifo_enqReq_wires_0_wget_BIT_18___d9 : DEF_toHostFifo_enqReq_ehrReg_0_BIT_18___d11);
  DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d27 = DEF_toHostFifo_enqReq_wires_1_whas____d4 ? (tUInt32)(262143u & DEF_toHostFifo_enqReq_wires_1_wget____d5) : (DEF_toHostFifo_enqReq_wires_0_whas____d7 ? (tUInt32)(262143u & DEF_toHostFifo_enqReq_wires_0_wget____d8) : DEF_toHostFifo_enqReq_ehrReg_0_BITS_17_TO_0___d25);
  DEF_IF_toHostFifo_enqReq_wires_2_whas_THEN_toHostF_ETC___d28 = DEF_toHostFifo_enqReq_wires_2_whas____d1 ? (tUInt32)(262143u & DEF_toHostFifo_enqReq_wires_2_wget____d2) : DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d27;
  DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_NOT_toH_ETC___d20 = DEF_toHostFifo_enqReq_wires_1_whas____d4 ? !DEF_toHostFifo_enqReq_wires_1_wget_BIT_18___d6 : (DEF_toHostFifo_enqReq_wires_0_whas____d7 ? !DEF_toHostFifo_enqReq_wires_0_wget_BIT_18___d9 : !DEF_toHostFifo_enqReq_ehrReg_0_BIT_18___d11);
  DEF_IF_toHostFifo_enqReq_wires_2_whas_THEN_toHostF_ETC___d30 = 524287u & ((((tUInt32)(DEF_toHostFifo_enqReq_wires_2_whas____d1 ? DEF_toHostFifo_enqReq_wires_2_wget_BIT_18___d3 : DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d13)) << 18u) | ((DEF_toHostFifo_enqReq_wires_2_whas____d1 ? !DEF_toHostFifo_enqReq_wires_2_wget_BIT_18___d3 : DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_NOT_toH_ETC___d20) ? DEF_IF_toHostFifo_enqReq_wires_2_whas_THEN_toHostF_ETC___d28 : DEF_IF_toHostFifo_enqReq_wires_2_whas_THEN_toHostF_ETC___d28));
  INST_toHostFifo_enqReq_ehrReg.METH_write(DEF_IF_toHostFifo_enqReq_wires_2_whas_THEN_toHostF_ETC___d30);
}

void MOD_mkCsrFile::RL_toHostFifo_deqReq_canonicalize()
{
  tUInt8 DEF_IF_toHostFifo_deqReq_wires_2_whas__1_THEN_toHo_ETC___d40;
  DEF_toHostFifo_deqReq_ehrReg___d37 = INST_toHostFifo_deqReq_ehrReg.METH_read();
  DEF_IF_toHostFifo_deqReq_wires_1_whas__3_THEN_toHo_ETC___d39 = INST_toHostFifo_deqReq_wires_1.METH_whas() ? INST_toHostFifo_deqReq_wires_1.METH_wget() : (INST_toHostFifo_deqReq_wires_0.METH_whas() ? INST_toHostFifo_deqReq_wires_0.METH_wget() : DEF_toHostFifo_deqReq_ehrReg___d37);
  DEF_IF_toHostFifo_deqReq_wires_2_whas__1_THEN_toHo_ETC___d40 = INST_toHostFifo_deqReq_wires_2.METH_whas() ? INST_toHostFifo_deqReq_wires_2.METH_wget() : DEF_IF_toHostFifo_deqReq_wires_1_whas__3_THEN_toHo_ETC___d39;
  INST_toHostFifo_deqReq_ehrReg.METH_write(DEF_IF_toHostFifo_deqReq_wires_2_whas__1_THEN_toHo_ETC___d40);
}

void MOD_mkCsrFile::RL_toHostFifo_clearReq_canonicalize()
{
  tUInt8 DEF_IF_toHostFifo_clearReq_wires_1_whas__1_THEN_to_ETC___d47;
  DEF_toHostFifo_clearReq_wires_0_whas____d43 = INST_toHostFifo_clearReq_wires_0.METH_whas();
  DEF_toHostFifo_clearReq_wires_0_wget____d44 = INST_toHostFifo_clearReq_wires_0.METH_wget();
  DEF_toHostFifo_clearReq_ehrReg___d45 = INST_toHostFifo_clearReq_ehrReg.METH_read();
  DEF_IF_toHostFifo_clearReq_wires_0_whas__3_THEN_to_ETC___d46 = DEF_toHostFifo_clearReq_wires_0_whas____d43 ? DEF_toHostFifo_clearReq_wires_0_wget____d44 : DEF_toHostFifo_clearReq_ehrReg___d45;
  DEF_IF_toHostFifo_clearReq_wires_1_whas__1_THEN_to_ETC___d47 = INST_toHostFifo_clearReq_wires_1.METH_whas() ? INST_toHostFifo_clearReq_wires_1.METH_wget() : DEF_IF_toHostFifo_clearReq_wires_0_whas__3_THEN_to_ETC___d46;
  INST_toHostFifo_clearReq_ehrReg.METH_write(DEF_IF_toHostFifo_clearReq_wires_1_whas__1_THEN_to_ETC___d47);
}

void MOD_mkCsrFile::RL_toHostFifo_canonicalize()
{
  tUInt32 DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d92;
  tUInt32 DEF__0_CONCAT_DONTCARE___d90;
  tUInt8 DEF_toHostFifo_clearReq_virtual_reg_1_read__8_OR_I_ETC___d70;
  tUInt8 DEF_toHostFifo_clearReq_virtual_reg_1_read__8_OR_I_ETC___d61;
  tUInt8 DEF_toHostFifo_clearReq_virtual_reg_1_read__8_OR_I_ETC___d75;
  tUInt8 DEF_toHostFifo_enqP_6_EQ_0_3_AND_toHostFifo_clearR_ETC___d85;
  tUInt8 DEF_toHostFifo_clearReq_virtual_reg_1_read__8_OR_I_ETC___d84;
  tUInt8 DEF_toHostFifo_enqP_6_EQ_1_8_AND_toHostFifo_clearR_ETC___d89;
  tUInt8 DEF_NOT_toHostFifo_clearReq_virtual_reg_1_read__8__ETC___d82;
  tUInt8 DEF_v__h4996;
  tUInt8 DEF_NOT_toHostFifo_enqReq_virtual_reg_2_read__3_4__ETC___d55;
  tUInt8 DEF_next_deqP___1__h5687;
  tUInt8 DEF_NOT_toHostFifo_deqReq_virtual_reg_2_read__2_3__ETC___d64;
  tUInt32 DEF_IF_toHostFifo_enqReq_virtual_reg_2_read__3_OR__ETC___d87;
  tUInt8 DEF_toHostFifo_clearReq_virtual_reg_1_read____d48;
  tUInt8 DEF_toHostFifo_enqReq_virtual_reg_2_read____d53;
  tUInt8 DEF_v__h4637;
  tUInt8 DEF__theResult_____2__h5282;
  tUInt8 DEF_IF_NOT_toHostFifo_deqReq_virtual_reg_2_read__2_ETC___d71;
  tUInt8 DEF_toHostFifo_enqP__h5265;
  tUInt8 DEF_toHostFifo_clearReq_virtual_reg_1_read__8_OR_I_ETC___d52;
  DEF_toHostFifo_empty__h5796 = INST_toHostFifo_empty.METH_read();
  DEF_toHostFifo_full__h5764 = INST_toHostFifo_full.METH_read();
  DEF_toHostFifo_enqP__h5265 = INST_toHostFifo_enqP.METH_read();
  DEF_toHostFifo_enqReq_virtual_reg_2_read____d53 = INST_toHostFifo_enqReq_virtual_reg_2.METH_read();
  DEF_toHostFifo_enqReq_wires_1_wget____d5 = INST_toHostFifo_enqReq_wires_1.METH_wget();
  DEF_toHostFifo_enqReq_wires_0_wget____d8 = INST_toHostFifo_enqReq_wires_0.METH_wget();
  DEF_toHostFifo_enqReq_ehrReg___d10 = INST_toHostFifo_enqReq_ehrReg.METH_read();
  DEF_toHostFifo_clearReq_wires_0_whas____d43 = INST_toHostFifo_clearReq_wires_0.METH_whas();
  DEF_toHostFifo_clearReq_virtual_reg_1_read____d48 = INST_toHostFifo_clearReq_virtual_reg_1.METH_read();
  DEF_toHostFifo_clearReq_wires_0_wget____d44 = INST_toHostFifo_clearReq_wires_0.METH_wget();
  DEF_toHostFifo_clearReq_ehrReg___d45 = INST_toHostFifo_clearReq_ehrReg.METH_read();
  DEF_toHostFifo_clearReq_virtual_reg_1_read__8_OR_I_ETC___d52 = DEF_toHostFifo_clearReq_virtual_reg_1_read____d48 || (DEF_toHostFifo_clearReq_wires_0_whas____d43 ? !DEF_toHostFifo_clearReq_wires_0_wget____d44 : !DEF_toHostFifo_clearReq_ehrReg___d45);
  DEF_IF_toHostFifo_clearReq_wires_0_whas__3_THEN_to_ETC___d46 = DEF_toHostFifo_clearReq_wires_0_whas____d43 ? DEF_toHostFifo_clearReq_wires_0_wget____d44 : DEF_toHostFifo_clearReq_ehrReg___d45;
  DEF_toHostFifo_deqReq_ehrReg___d37 = INST_toHostFifo_deqReq_ehrReg.METH_read();
  DEF_toHostFifo_enqReq_wires_1_whas____d4 = INST_toHostFifo_enqReq_wires_1.METH_whas();
  DEF_toHostFifo_enqReq_wires_0_whas____d7 = INST_toHostFifo_enqReq_wires_0.METH_whas();
  DEF_x__h7622 = INST_toHostFifo_deqP.METH_read();
  DEF_toHostFifo_enqReq_ehrReg_0_BITS_17_TO_0___d25 = (tUInt32)(262143u & DEF_toHostFifo_enqReq_ehrReg___d10);
  DEF_toHostFifo_enqReq_ehrReg_0_BIT_18___d11 = (tUInt8)(DEF_toHostFifo_enqReq_ehrReg___d10 >> 18u);
  DEF_toHostFifo_enqReq_wires_0_wget_BIT_18___d9 = (tUInt8)(DEF_toHostFifo_enqReq_wires_0_wget____d8 >> 18u);
  DEF_toHostFifo_enqReq_wires_1_wget_BIT_18___d6 = (tUInt8)(DEF_toHostFifo_enqReq_wires_1_wget____d5 >> 18u);
  DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d13 = DEF_toHostFifo_enqReq_wires_1_whas____d4 ? DEF_toHostFifo_enqReq_wires_1_wget_BIT_18___d6 : (DEF_toHostFifo_enqReq_wires_0_whas____d7 ? DEF_toHostFifo_enqReq_wires_0_wget_BIT_18___d9 : DEF_toHostFifo_enqReq_ehrReg_0_BIT_18___d11);
  DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d27 = DEF_toHostFifo_enqReq_wires_1_whas____d4 ? (tUInt32)(262143u & DEF_toHostFifo_enqReq_wires_1_wget____d5) : (DEF_toHostFifo_enqReq_wires_0_whas____d7 ? (tUInt32)(262143u & DEF_toHostFifo_enqReq_wires_0_wget____d8) : DEF_toHostFifo_enqReq_ehrReg_0_BITS_17_TO_0___d25);
  DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_NOT_toH_ETC___d20 = DEF_toHostFifo_enqReq_wires_1_whas____d4 ? !DEF_toHostFifo_enqReq_wires_1_wget_BIT_18___d6 : (DEF_toHostFifo_enqReq_wires_0_whas____d7 ? !DEF_toHostFifo_enqReq_wires_0_wget_BIT_18___d9 : !DEF_toHostFifo_enqReq_ehrReg_0_BIT_18___d11);
  DEF_IF_toHostFifo_enqReq_virtual_reg_2_read__3_OR__ETC___d87 = DEF_toHostFifo_enqReq_virtual_reg_2_read____d53 || DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_NOT_toH_ETC___d20 ? DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d27 : DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d27;
  DEF_next_deqP___1__h5687 = !DEF_x__h7622 && (tUInt8)1u & (DEF_x__h7622 + (tUInt8)1u);
  DEF_NOT_toHostFifo_enqReq_virtual_reg_2_read__3_4__ETC___d55 = !DEF_toHostFifo_enqReq_virtual_reg_2_read____d53 && DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d13;
  DEF_v__h4996 = !DEF_toHostFifo_enqP__h5265 && (tUInt8)1u & (DEF_toHostFifo_enqP__h5265 + (tUInt8)1u);
  DEF_v__h4637 = DEF_NOT_toHostFifo_enqReq_virtual_reg_2_read__3_4__ETC___d55 ? DEF_v__h4996 : DEF_toHostFifo_enqP__h5265;
  DEF_IF_toHostFifo_deqReq_wires_1_whas__3_THEN_toHo_ETC___d39 = INST_toHostFifo_deqReq_wires_1.METH_whas() ? INST_toHostFifo_deqReq_wires_1.METH_wget() : (INST_toHostFifo_deqReq_wires_0.METH_whas() ? INST_toHostFifo_deqReq_wires_0.METH_wget() : DEF_toHostFifo_deqReq_ehrReg___d37);
  DEF_NOT_toHostFifo_deqReq_virtual_reg_2_read__2_3__ETC___d64 = !INST_toHostFifo_deqReq_virtual_reg_2.METH_read() && DEF_IF_toHostFifo_deqReq_wires_1_whas__3_THEN_toHo_ETC___d39;
  DEF__theResult_____2__h5282 = DEF_NOT_toHostFifo_deqReq_virtual_reg_2_read__2_3__ETC___d64 ? DEF_next_deqP___1__h5687 : DEF_x__h7622;
  DEF_IF_NOT_toHostFifo_deqReq_virtual_reg_2_read__2_ETC___d71 = DEF__theResult_____2__h5282 == DEF_v__h4637;
  DEF_NOT_toHostFifo_clearReq_virtual_reg_1_read__8__ETC___d82 = (!DEF_toHostFifo_clearReq_virtual_reg_1_read____d48 && DEF_IF_toHostFifo_clearReq_wires_0_whas__3_THEN_to_ETC___d46) || (DEF_IF_NOT_toHostFifo_deqReq_virtual_reg_2_read__2_ETC___d71 && (DEF_NOT_toHostFifo_enqReq_virtual_reg_2_read__3_4__ETC___d55 ? DEF_toHostFifo_empty__h5796 : DEF_NOT_toHostFifo_deqReq_virtual_reg_2_read__2_3__ETC___d64 || DEF_toHostFifo_empty__h5796));
  DEF_toHostFifo_clearReq_virtual_reg_1_read__8_OR_I_ETC___d84 = DEF_toHostFifo_clearReq_virtual_reg_1_read__8_OR_I_ETC___d52 && DEF_NOT_toHostFifo_enqReq_virtual_reg_2_read__3_4__ETC___d55;
  DEF_toHostFifo_enqP_6_EQ_1_8_AND_toHostFifo_clearR_ETC___d89 = DEF_toHostFifo_enqP__h5265 == (tUInt8)1u && DEF_toHostFifo_clearReq_virtual_reg_1_read__8_OR_I_ETC___d84;
  DEF_toHostFifo_enqP_6_EQ_0_3_AND_toHostFifo_clearR_ETC___d85 = DEF_toHostFifo_enqP__h5265 == (tUInt8)0u && DEF_toHostFifo_clearReq_virtual_reg_1_read__8_OR_I_ETC___d84;
  DEF_toHostFifo_clearReq_virtual_reg_1_read__8_OR_I_ETC___d75 = DEF_toHostFifo_clearReq_virtual_reg_1_read__8_OR_I_ETC___d52 && (DEF_IF_NOT_toHostFifo_deqReq_virtual_reg_2_read__2_ETC___d71 && (DEF_NOT_toHostFifo_enqReq_virtual_reg_2_read__3_4__ETC___d55 || DEF_toHostFifo_full__h5764));
  DEF_toHostFifo_clearReq_virtual_reg_1_read__8_OR_I_ETC___d61 = DEF_toHostFifo_clearReq_virtual_reg_1_read__8_OR_I_ETC___d52 && DEF_v__h4637;
  DEF_toHostFifo_clearReq_virtual_reg_1_read__8_OR_I_ETC___d70 = DEF_toHostFifo_clearReq_virtual_reg_1_read__8_OR_I_ETC___d52 && DEF__theResult_____2__h5282;
  DEF__0_CONCAT_DONTCARE___d90 = 174762u;
  DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d92 = 524287u & ((((tUInt32)(DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d13)) << 18u) | (DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_NOT_toH_ETC___d20 ? DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d27 : DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d27));
  INST_toHostFifo_enqP.METH_write(DEF_toHostFifo_clearReq_virtual_reg_1_read__8_OR_I_ETC___d61);
  INST_toHostFifo_deqP.METH_write(DEF_toHostFifo_clearReq_virtual_reg_1_read__8_OR_I_ETC___d70);
  INST_toHostFifo_full.METH_write(DEF_toHostFifo_clearReq_virtual_reg_1_read__8_OR_I_ETC___d75);
  INST_toHostFifo_empty.METH_write(DEF_NOT_toHostFifo_clearReq_virtual_reg_1_read__8__ETC___d82);
  if (DEF_toHostFifo_enqP_6_EQ_0_3_AND_toHostFifo_clearR_ETC___d85)
    INST_toHostFifo_data_0.METH_write(DEF_IF_toHostFifo_enqReq_virtual_reg_2_read__3_OR__ETC___d87);
  if (DEF_toHostFifo_enqP_6_EQ_1_8_AND_toHostFifo_clearR_ETC___d89)
    INST_toHostFifo_data_1.METH_write(DEF_IF_toHostFifo_enqReq_virtual_reg_2_read__3_OR__ETC___d87);
  INST_toHostFifo_clearReq_ignored_wires_1.METH_wset(DEF_IF_toHostFifo_clearReq_wires_0_whas__3_THEN_to_ETC___d46);
  INST_toHostFifo_clearReq_wires_1.METH_wset((tUInt8)0u);
  INST_toHostFifo_clearReq_virtual_reg_1.METH_write((tUInt8)0u);
  INST_toHostFifo_enqReq_wires_2.METH_wset(DEF__0_CONCAT_DONTCARE___d90);
  INST_toHostFifo_enqReq_ignored_wires_2.METH_wset(DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d92);
  INST_toHostFifo_enqReq_virtual_reg_2.METH_write((tUInt8)0u);
  INST_toHostFifo_deqReq_wires_2.METH_wset((tUInt8)0u);
  INST_toHostFifo_deqReq_virtual_reg_2.METH_write((tUInt8)0u);
  INST_toHostFifo_deqReq_ignored_wires_2.METH_wset(DEF_IF_toHostFifo_deqReq_wires_1_whas__3_THEN_toHo_ETC___d39);
}

void MOD_mkCsrFile::RL_count()
{
  tUInt32 DEF_x__h6913;
  DEF__read__h169 = INST_cycles.METH_read();
  DEF_x__h6913 = DEF__read__h169 + 1u;
  INST_cycles.METH_write(DEF_x__h6913);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,32", &__str_literal_1, DEF__read__h169);
}


/* Methods */

void MOD_mkCsrFile::METH_start(tUInt32 ARG_start_id)
{
  PORT_EN_start = (tUInt8)1u;
  DEF_WILL_FIRE_start = (tUInt8)1u;
  PORT_start_id = ARG_start_id;
  INST_startReg.METH_write((tUInt8)1u);
  INST_cycles.METH_write(0u);
  INST_coreId.METH_write(ARG_start_id);
}

tUInt8 MOD_mkCsrFile::METH_RDY_start()
{
  DEF_startReg_read____d93 = INST_startReg.METH_read();
  DEF_CAN_FIRE_start = !DEF_startReg_read____d93;
  PORT_RDY_start = DEF_CAN_FIRE_start;
  return PORT_RDY_start;
}

tUInt8 MOD_mkCsrFile::METH_started()
{
  DEF_startReg_read____d93 = INST_startReg.METH_read();
  PORT_started = DEF_startReg_read____d93;
  return PORT_started;
}

tUInt8 MOD_mkCsrFile::METH_RDY_started()
{
  DEF_CAN_FIRE_started = (tUInt8)1u;
  PORT_RDY_started = DEF_CAN_FIRE_started;
  return PORT_RDY_started;
}

tUInt32 MOD_mkCsrFile::METH_rd(tUInt32 ARG_rd_idx)
{
  tUInt32 DEF__read__h219;
  PORT_rd_idx = ARG_rd_idx;
  DEF__read__h219 = INST_coreId.METH_read();
  DEF__read__h169 = INST_cycles.METH_read();
  DEF__read__h117 = INST_numInsts.METH_read();
  switch (ARG_rd_idx) {
  case 3072u:
    PORT_rd = DEF__read__h169;
    break;
  case 3074u:
    PORT_rd = DEF__read__h117;
    break;
  default:
    PORT_rd = DEF__read__h219;
  }
  return PORT_rd;
}

tUInt8 MOD_mkCsrFile::METH_RDY_rd()
{
  DEF_CAN_FIRE_rd = (tUInt8)1u;
  PORT_RDY_rd = DEF_CAN_FIRE_rd;
  return PORT_RDY_rd;
}

void MOD_mkCsrFile::METH_wr(tUInt32 ARG_wr_idx, tUInt32 ARG_wr_val)
{
  tUInt32 DEF_toHostFifo_enqReq_ehrReg_0_BIT_18_1_CONCAT_IF__ETC___d110;
  tUInt32 DEF__1_CONCAT_wr_val_BITS_17_TO_0_07___d108;
  tUInt32 DEF_x__h7415;
  tUInt8 DEF_wr_idx_BIT_12_03_AND_wr_idx_BITS_11_TO_0_04_EQ_ETC___d106;
  tUInt32 DEF_x__h7128;
  PORT_EN_wr = (tUInt8)1u;
  DEF_WILL_FIRE_wr = (tUInt8)1u;
  PORT_wr_idx = ARG_wr_idx;
  PORT_wr_val = ARG_wr_val;
  DEF__read__h117 = INST_numInsts.METH_read();
  DEF_toHostFifo_enqReq_ehrReg___d10 = INST_toHostFifo_enqReq_ehrReg.METH_read();
  DEF_toHostFifo_enqReq_ehrReg_0_BITS_17_TO_0___d25 = (tUInt32)(262143u & DEF_toHostFifo_enqReq_ehrReg___d10);
  DEF_x__h7128 = (tUInt32)(4095u & ARG_wr_idx);
  DEF_toHostFifo_enqReq_ehrReg_0_BIT_18___d11 = (tUInt8)(DEF_toHostFifo_enqReq_ehrReg___d10 >> 18u);
  DEF_wr_idx_BIT_12_03_AND_wr_idx_BITS_11_TO_0_04_EQ_ETC___d106 = (tUInt8)(ARG_wr_idx >> 12u) && DEF_x__h7128 == 1920u;
  DEF_x__h7415 = DEF__read__h117 + 1u;
  DEF__1_CONCAT_wr_val_BITS_17_TO_0_07___d108 = 524287u & ((((tUInt32)((tUInt8)1u)) << 18u) | (tUInt32)(262143u & ARG_wr_val));
  DEF_toHostFifo_enqReq_ehrReg_0_BIT_18_1_CONCAT_IF__ETC___d110 = 524287u & ((((tUInt32)(DEF_toHostFifo_enqReq_ehrReg_0_BIT_18___d11)) << 18u) | (DEF_toHostFifo_enqReq_ehrReg_0_BIT_18___d11 ? DEF_toHostFifo_enqReq_ehrReg_0_BITS_17_TO_0___d25 : DEF_toHostFifo_enqReq_ehrReg_0_BITS_17_TO_0___d25));
  if (DEF_wr_idx_BIT_12_03_AND_wr_idx_BITS_11_TO_0_04_EQ_ETC___d106)
    INST_toHostFifo_enqReq_wires_0.METH_wset(DEF__1_CONCAT_wr_val_BITS_17_TO_0_07___d108);
  if (DEF_wr_idx_BIT_12_03_AND_wr_idx_BITS_11_TO_0_04_EQ_ETC___d106)
    INST_toHostFifo_enqReq_ignored_wires_0.METH_wset(DEF_toHostFifo_enqReq_ehrReg_0_BIT_18_1_CONCAT_IF__ETC___d110);
  if (DEF_wr_idx_BIT_12_03_AND_wr_idx_BITS_11_TO_0_04_EQ_ETC___d106)
    INST_toHostFifo_enqReq_virtual_reg_0.METH_write((tUInt8)0u);
  INST_numInsts.METH_write(DEF_x__h7415);
}

tUInt8 MOD_mkCsrFile::METH_RDY_wr()
{
  DEF_toHostFifo_full__h5764 = INST_toHostFifo_full.METH_read();
  DEF_CAN_FIRE_wr = !DEF_toHostFifo_full__h5764;
  PORT_RDY_wr = DEF_CAN_FIRE_wr;
  return PORT_RDY_wr;
}

tUInt32 MOD_mkCsrFile::METH_cpuToHost()
{
  tUInt8 DEF_SEL_ARR_toHostFifo_data_0_12_BITS_17_TO_16_13__ETC___d117;
  tUInt32 DEF_SEL_ARR_toHostFifo_data_0_12_BITS_15_TO_0_18_t_ETC___d121;
  tUInt32 DEF__read_data__h7640;
  tUInt32 DEF__read_data__h7636;
  tUInt32 DEF_toHostFifo_data_0___d112;
  tUInt32 DEF_toHostFifo_data_1___d114;
  PORT_EN_cpuToHost = (tUInt8)1u;
  DEF_WILL_FIRE_cpuToHost = (tUInt8)1u;
  DEF_toHostFifo_data_1___d114 = INST_toHostFifo_data_1.METH_read();
  DEF_toHostFifo_data_0___d112 = INST_toHostFifo_data_0.METH_read();
  DEF_toHostFifo_deqReq_ehrReg___d37 = INST_toHostFifo_deqReq_ehrReg.METH_read();
  DEF_x__h7622 = INST_toHostFifo_deqP.METH_read();
  DEF__read_data__h7636 = (tUInt32)(65535u & DEF_toHostFifo_data_0___d112);
  DEF__read_data__h7640 = (tUInt32)(65535u & DEF_toHostFifo_data_1___d114);
  switch (DEF_x__h7622) {
  case (tUInt8)0u:
    DEF_SEL_ARR_toHostFifo_data_0_12_BITS_15_TO_0_18_t_ETC___d121 = DEF__read_data__h7636;
    break;
  case (tUInt8)1u:
    DEF_SEL_ARR_toHostFifo_data_0_12_BITS_15_TO_0_18_t_ETC___d121 = DEF__read_data__h7640;
    break;
  default:
    DEF_SEL_ARR_toHostFifo_data_0_12_BITS_15_TO_0_18_t_ETC___d121 = 43690u;
  }
  switch (DEF_x__h7622) {
  case (tUInt8)0u:
    DEF_SEL_ARR_toHostFifo_data_0_12_BITS_17_TO_16_13__ETC___d117 = (tUInt8)(DEF_toHostFifo_data_0___d112 >> 16u);
    break;
  case (tUInt8)1u:
    DEF_SEL_ARR_toHostFifo_data_0_12_BITS_17_TO_16_13__ETC___d117 = (tUInt8)(DEF_toHostFifo_data_1___d114 >> 16u);
    break;
  default:
    DEF_SEL_ARR_toHostFifo_data_0_12_BITS_17_TO_16_13__ETC___d117 = (tUInt8)2u;
  }
  PORT_cpuToHost = 262143u & ((((tUInt32)(DEF_SEL_ARR_toHostFifo_data_0_12_BITS_17_TO_16_13__ETC___d117)) << 16u) | DEF_SEL_ARR_toHostFifo_data_0_12_BITS_15_TO_0_18_t_ETC___d121);
  INST_toHostFifo_deqReq_wires_0.METH_wset((tUInt8)1u);
  INST_toHostFifo_deqReq_virtual_reg_0.METH_write((tUInt8)0u);
  INST_toHostFifo_deqReq_ignored_wires_0.METH_wset(DEF_toHostFifo_deqReq_ehrReg___d37);
  return PORT_cpuToHost;
}

tUInt8 MOD_mkCsrFile::METH_RDY_cpuToHost()
{
  DEF_toHostFifo_empty__h5796 = INST_toHostFifo_empty.METH_read();
  DEF_CAN_FIRE_cpuToHost = !DEF_toHostFifo_empty__h5796;
  PORT_RDY_cpuToHost = DEF_CAN_FIRE_cpuToHost;
  return PORT_RDY_cpuToHost;
}


/* Reset routines */

void MOD_mkCsrFile::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_toHostFifo_full.reset_RST(ARG_rst_in);
  INST_toHostFifo_enqReq_ehrReg.reset_RST(ARG_rst_in);
  INST_toHostFifo_enqP.reset_RST(ARG_rst_in);
  INST_toHostFifo_empty.reset_RST(ARG_rst_in);
  INST_toHostFifo_deqReq_ehrReg.reset_RST(ARG_rst_in);
  INST_toHostFifo_deqP.reset_RST(ARG_rst_in);
  INST_toHostFifo_clearReq_ehrReg.reset_RST(ARG_rst_in);
  INST_startReg.reset_RST(ARG_rst_in);
  INST_numInsts.reset_RST(ARG_rst_in);
  INST_cycles.reset_RST(ARG_rst_in);
  INST_coreId.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkCsrFile::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkCsrFile::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_coreId.dump_state(indent + 2u);
  INST_cycles.dump_state(indent + 2u);
  INST_numInsts.dump_state(indent + 2u);
  INST_startReg.dump_state(indent + 2u);
  INST_toHostFifo_clearReq_ehrReg.dump_state(indent + 2u);
  INST_toHostFifo_clearReq_ignored_wires_0.dump_state(indent + 2u);
  INST_toHostFifo_clearReq_ignored_wires_1.dump_state(indent + 2u);
  INST_toHostFifo_clearReq_virtual_reg_0.dump_state(indent + 2u);
  INST_toHostFifo_clearReq_virtual_reg_1.dump_state(indent + 2u);
  INST_toHostFifo_clearReq_wires_0.dump_state(indent + 2u);
  INST_toHostFifo_clearReq_wires_1.dump_state(indent + 2u);
  INST_toHostFifo_data_0.dump_state(indent + 2u);
  INST_toHostFifo_data_1.dump_state(indent + 2u);
  INST_toHostFifo_deqP.dump_state(indent + 2u);
  INST_toHostFifo_deqReq_ehrReg.dump_state(indent + 2u);
  INST_toHostFifo_deqReq_ignored_wires_0.dump_state(indent + 2u);
  INST_toHostFifo_deqReq_ignored_wires_1.dump_state(indent + 2u);
  INST_toHostFifo_deqReq_ignored_wires_2.dump_state(indent + 2u);
  INST_toHostFifo_deqReq_virtual_reg_0.dump_state(indent + 2u);
  INST_toHostFifo_deqReq_virtual_reg_1.dump_state(indent + 2u);
  INST_toHostFifo_deqReq_virtual_reg_2.dump_state(indent + 2u);
  INST_toHostFifo_deqReq_wires_0.dump_state(indent + 2u);
  INST_toHostFifo_deqReq_wires_1.dump_state(indent + 2u);
  INST_toHostFifo_deqReq_wires_2.dump_state(indent + 2u);
  INST_toHostFifo_empty.dump_state(indent + 2u);
  INST_toHostFifo_enqP.dump_state(indent + 2u);
  INST_toHostFifo_enqReq_ehrReg.dump_state(indent + 2u);
  INST_toHostFifo_enqReq_ignored_wires_0.dump_state(indent + 2u);
  INST_toHostFifo_enqReq_ignored_wires_1.dump_state(indent + 2u);
  INST_toHostFifo_enqReq_ignored_wires_2.dump_state(indent + 2u);
  INST_toHostFifo_enqReq_virtual_reg_0.dump_state(indent + 2u);
  INST_toHostFifo_enqReq_virtual_reg_1.dump_state(indent + 2u);
  INST_toHostFifo_enqReq_virtual_reg_2.dump_state(indent + 2u);
  INST_toHostFifo_enqReq_wires_0.dump_state(indent + 2u);
  INST_toHostFifo_enqReq_wires_1.dump_state(indent + 2u);
  INST_toHostFifo_enqReq_wires_2.dump_state(indent + 2u);
  INST_toHostFifo_full.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkCsrFile::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 95u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_count", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_toHostFifo_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_toHostFifo_clearReq_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_toHostFifo_deqReq_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_toHostFifo_enqReq_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_cpuToHost", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_rd", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_start", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_started", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_wr", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_toHostFifo_clearReq_wires_0_whas__3_THEN_to_ETC___d46", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_toHostFifo_deqReq_wires_1_whas__3_THEN_toHo_ETC___d39", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_toHostFifo_enqReq_wires_1_whas_THEN_NOT_toH_ETC___d20", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d13", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d27", 18u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_count", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_toHostFifo_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_toHostFifo_clearReq_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_toHostFifo_deqReq_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_toHostFifo_enqReq_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_cpuToHost", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_start", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_wr", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "_read__h117", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "_read__h169", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "startReg_read____d93", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "toHostFifo_clearReq_ehrReg___d45", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "toHostFifo_clearReq_wires_0_wget____d44", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "toHostFifo_clearReq_wires_0_whas____d43", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "toHostFifo_deqReq_ehrReg___d37", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "toHostFifo_empty__h5796", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "toHostFifo_enqReq_ehrReg_0_BITS_17_TO_0___d25", 18u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "toHostFifo_enqReq_ehrReg_0_BIT_18___d11", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "toHostFifo_enqReq_ehrReg___d10", 19u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "toHostFifo_enqReq_wires_0_wget_BIT_18___d9", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "toHostFifo_enqReq_wires_0_wget____d8", 19u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "toHostFifo_enqReq_wires_0_whas____d7", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "toHostFifo_enqReq_wires_1_wget_BIT_18___d6", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "toHostFifo_enqReq_wires_1_wget____d5", 19u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "toHostFifo_enqReq_wires_1_whas____d4", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "toHostFifo_full__h5764", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h7622", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "EN_cpuToHost", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "EN_start", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "EN_wr", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_cpuToHost", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_rd", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_start", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_started", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_wr", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "cpuToHost", 18u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "rd", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "rd_idx", 12u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "start_id", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "started", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "wr_idx", 13u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "wr_val", 32u);
  num = INST_coreId.dump_VCD_defs(num);
  num = INST_cycles.dump_VCD_defs(num);
  num = INST_numInsts.dump_VCD_defs(num);
  num = INST_startReg.dump_VCD_defs(num);
  num = INST_toHostFifo_clearReq_ehrReg.dump_VCD_defs(num);
  num = INST_toHostFifo_clearReq_ignored_wires_0.dump_VCD_defs(num);
  num = INST_toHostFifo_clearReq_ignored_wires_1.dump_VCD_defs(num);
  num = INST_toHostFifo_clearReq_virtual_reg_0.dump_VCD_defs(num);
  num = INST_toHostFifo_clearReq_virtual_reg_1.dump_VCD_defs(num);
  num = INST_toHostFifo_clearReq_wires_0.dump_VCD_defs(num);
  num = INST_toHostFifo_clearReq_wires_1.dump_VCD_defs(num);
  num = INST_toHostFifo_data_0.dump_VCD_defs(num);
  num = INST_toHostFifo_data_1.dump_VCD_defs(num);
  num = INST_toHostFifo_deqP.dump_VCD_defs(num);
  num = INST_toHostFifo_deqReq_ehrReg.dump_VCD_defs(num);
  num = INST_toHostFifo_deqReq_ignored_wires_0.dump_VCD_defs(num);
  num = INST_toHostFifo_deqReq_ignored_wires_1.dump_VCD_defs(num);
  num = INST_toHostFifo_deqReq_ignored_wires_2.dump_VCD_defs(num);
  num = INST_toHostFifo_deqReq_virtual_reg_0.dump_VCD_defs(num);
  num = INST_toHostFifo_deqReq_virtual_reg_1.dump_VCD_defs(num);
  num = INST_toHostFifo_deqReq_virtual_reg_2.dump_VCD_defs(num);
  num = INST_toHostFifo_deqReq_wires_0.dump_VCD_defs(num);
  num = INST_toHostFifo_deqReq_wires_1.dump_VCD_defs(num);
  num = INST_toHostFifo_deqReq_wires_2.dump_VCD_defs(num);
  num = INST_toHostFifo_empty.dump_VCD_defs(num);
  num = INST_toHostFifo_enqP.dump_VCD_defs(num);
  num = INST_toHostFifo_enqReq_ehrReg.dump_VCD_defs(num);
  num = INST_toHostFifo_enqReq_ignored_wires_0.dump_VCD_defs(num);
  num = INST_toHostFifo_enqReq_ignored_wires_1.dump_VCD_defs(num);
  num = INST_toHostFifo_enqReq_ignored_wires_2.dump_VCD_defs(num);
  num = INST_toHostFifo_enqReq_virtual_reg_0.dump_VCD_defs(num);
  num = INST_toHostFifo_enqReq_virtual_reg_1.dump_VCD_defs(num);
  num = INST_toHostFifo_enqReq_virtual_reg_2.dump_VCD_defs(num);
  num = INST_toHostFifo_enqReq_wires_0.dump_VCD_defs(num);
  num = INST_toHostFifo_enqReq_wires_1.dump_VCD_defs(num);
  num = INST_toHostFifo_enqReq_wires_2.dump_VCD_defs(num);
  num = INST_toHostFifo_full.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkCsrFile::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkCsrFile &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkCsrFile::vcd_defs(tVCDDumpType dt, MOD_mkCsrFile &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 18u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 18u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 19u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 19u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 19u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 18u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 12u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 13u);
    vcd_write_x(sim_hdl, num++, 32u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_CAN_FIRE_RL_count) != DEF_CAN_FIRE_RL_count)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_count, 1u);
	backing.DEF_CAN_FIRE_RL_count = DEF_CAN_FIRE_RL_count;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_toHostFifo_canonicalize) != DEF_CAN_FIRE_RL_toHostFifo_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_toHostFifo_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_toHostFifo_canonicalize = DEF_CAN_FIRE_RL_toHostFifo_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_toHostFifo_clearReq_canonicalize) != DEF_CAN_FIRE_RL_toHostFifo_clearReq_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_toHostFifo_clearReq_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_toHostFifo_clearReq_canonicalize = DEF_CAN_FIRE_RL_toHostFifo_clearReq_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_toHostFifo_deqReq_canonicalize) != DEF_CAN_FIRE_RL_toHostFifo_deqReq_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_toHostFifo_deqReq_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_toHostFifo_deqReq_canonicalize = DEF_CAN_FIRE_RL_toHostFifo_deqReq_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_toHostFifo_enqReq_canonicalize) != DEF_CAN_FIRE_RL_toHostFifo_enqReq_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_toHostFifo_enqReq_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_toHostFifo_enqReq_canonicalize = DEF_CAN_FIRE_RL_toHostFifo_enqReq_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_cpuToHost) != DEF_CAN_FIRE_cpuToHost)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_cpuToHost, 1u);
	backing.DEF_CAN_FIRE_cpuToHost = DEF_CAN_FIRE_cpuToHost;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_rd) != DEF_CAN_FIRE_rd)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_rd, 1u);
	backing.DEF_CAN_FIRE_rd = DEF_CAN_FIRE_rd;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_start) != DEF_CAN_FIRE_start)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_start, 1u);
	backing.DEF_CAN_FIRE_start = DEF_CAN_FIRE_start;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_started) != DEF_CAN_FIRE_started)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_started, 1u);
	backing.DEF_CAN_FIRE_started = DEF_CAN_FIRE_started;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_wr) != DEF_CAN_FIRE_wr)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_wr, 1u);
	backing.DEF_CAN_FIRE_wr = DEF_CAN_FIRE_wr;
      }
      ++num;
      if ((backing.DEF_IF_toHostFifo_clearReq_wires_0_whas__3_THEN_to_ETC___d46) != DEF_IF_toHostFifo_clearReq_wires_0_whas__3_THEN_to_ETC___d46)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_toHostFifo_clearReq_wires_0_whas__3_THEN_to_ETC___d46, 1u);
	backing.DEF_IF_toHostFifo_clearReq_wires_0_whas__3_THEN_to_ETC___d46 = DEF_IF_toHostFifo_clearReq_wires_0_whas__3_THEN_to_ETC___d46;
      }
      ++num;
      if ((backing.DEF_IF_toHostFifo_deqReq_wires_1_whas__3_THEN_toHo_ETC___d39) != DEF_IF_toHostFifo_deqReq_wires_1_whas__3_THEN_toHo_ETC___d39)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_toHostFifo_deqReq_wires_1_whas__3_THEN_toHo_ETC___d39, 1u);
	backing.DEF_IF_toHostFifo_deqReq_wires_1_whas__3_THEN_toHo_ETC___d39 = DEF_IF_toHostFifo_deqReq_wires_1_whas__3_THEN_toHo_ETC___d39;
      }
      ++num;
      if ((backing.DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_NOT_toH_ETC___d20) != DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_NOT_toH_ETC___d20)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_NOT_toH_ETC___d20, 1u);
	backing.DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_NOT_toH_ETC___d20 = DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_NOT_toH_ETC___d20;
      }
      ++num;
      if ((backing.DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d13) != DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d13)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d13, 1u);
	backing.DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d13 = DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d13;
      }
      ++num;
      if ((backing.DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d27) != DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d27)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d27, 18u);
	backing.DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d27 = DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d27;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_count) != DEF_WILL_FIRE_RL_count)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_count, 1u);
	backing.DEF_WILL_FIRE_RL_count = DEF_WILL_FIRE_RL_count;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_toHostFifo_canonicalize) != DEF_WILL_FIRE_RL_toHostFifo_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_toHostFifo_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_toHostFifo_canonicalize = DEF_WILL_FIRE_RL_toHostFifo_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_toHostFifo_clearReq_canonicalize) != DEF_WILL_FIRE_RL_toHostFifo_clearReq_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_toHostFifo_clearReq_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_toHostFifo_clearReq_canonicalize = DEF_WILL_FIRE_RL_toHostFifo_clearReq_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_toHostFifo_deqReq_canonicalize) != DEF_WILL_FIRE_RL_toHostFifo_deqReq_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_toHostFifo_deqReq_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_toHostFifo_deqReq_canonicalize = DEF_WILL_FIRE_RL_toHostFifo_deqReq_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_toHostFifo_enqReq_canonicalize) != DEF_WILL_FIRE_RL_toHostFifo_enqReq_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_toHostFifo_enqReq_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_toHostFifo_enqReq_canonicalize = DEF_WILL_FIRE_RL_toHostFifo_enqReq_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_cpuToHost) != DEF_WILL_FIRE_cpuToHost)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_cpuToHost, 1u);
	backing.DEF_WILL_FIRE_cpuToHost = DEF_WILL_FIRE_cpuToHost;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_start) != DEF_WILL_FIRE_start)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_start, 1u);
	backing.DEF_WILL_FIRE_start = DEF_WILL_FIRE_start;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_wr) != DEF_WILL_FIRE_wr)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_wr, 1u);
	backing.DEF_WILL_FIRE_wr = DEF_WILL_FIRE_wr;
      }
      ++num;
      if ((backing.DEF__read__h117) != DEF__read__h117)
      {
	vcd_write_val(sim_hdl, num, DEF__read__h117, 32u);
	backing.DEF__read__h117 = DEF__read__h117;
      }
      ++num;
      if ((backing.DEF__read__h169) != DEF__read__h169)
      {
	vcd_write_val(sim_hdl, num, DEF__read__h169, 32u);
	backing.DEF__read__h169 = DEF__read__h169;
      }
      ++num;
      if ((backing.DEF_startReg_read____d93) != DEF_startReg_read____d93)
      {
	vcd_write_val(sim_hdl, num, DEF_startReg_read____d93, 1u);
	backing.DEF_startReg_read____d93 = DEF_startReg_read____d93;
      }
      ++num;
      if ((backing.DEF_toHostFifo_clearReq_ehrReg___d45) != DEF_toHostFifo_clearReq_ehrReg___d45)
      {
	vcd_write_val(sim_hdl, num, DEF_toHostFifo_clearReq_ehrReg___d45, 1u);
	backing.DEF_toHostFifo_clearReq_ehrReg___d45 = DEF_toHostFifo_clearReq_ehrReg___d45;
      }
      ++num;
      if ((backing.DEF_toHostFifo_clearReq_wires_0_wget____d44) != DEF_toHostFifo_clearReq_wires_0_wget____d44)
      {
	vcd_write_val(sim_hdl, num, DEF_toHostFifo_clearReq_wires_0_wget____d44, 1u);
	backing.DEF_toHostFifo_clearReq_wires_0_wget____d44 = DEF_toHostFifo_clearReq_wires_0_wget____d44;
      }
      ++num;
      if ((backing.DEF_toHostFifo_clearReq_wires_0_whas____d43) != DEF_toHostFifo_clearReq_wires_0_whas____d43)
      {
	vcd_write_val(sim_hdl, num, DEF_toHostFifo_clearReq_wires_0_whas____d43, 1u);
	backing.DEF_toHostFifo_clearReq_wires_0_whas____d43 = DEF_toHostFifo_clearReq_wires_0_whas____d43;
      }
      ++num;
      if ((backing.DEF_toHostFifo_deqReq_ehrReg___d37) != DEF_toHostFifo_deqReq_ehrReg___d37)
      {
	vcd_write_val(sim_hdl, num, DEF_toHostFifo_deqReq_ehrReg___d37, 1u);
	backing.DEF_toHostFifo_deqReq_ehrReg___d37 = DEF_toHostFifo_deqReq_ehrReg___d37;
      }
      ++num;
      if ((backing.DEF_toHostFifo_empty__h5796) != DEF_toHostFifo_empty__h5796)
      {
	vcd_write_val(sim_hdl, num, DEF_toHostFifo_empty__h5796, 1u);
	backing.DEF_toHostFifo_empty__h5796 = DEF_toHostFifo_empty__h5796;
      }
      ++num;
      if ((backing.DEF_toHostFifo_enqReq_ehrReg_0_BITS_17_TO_0___d25) != DEF_toHostFifo_enqReq_ehrReg_0_BITS_17_TO_0___d25)
      {
	vcd_write_val(sim_hdl, num, DEF_toHostFifo_enqReq_ehrReg_0_BITS_17_TO_0___d25, 18u);
	backing.DEF_toHostFifo_enqReq_ehrReg_0_BITS_17_TO_0___d25 = DEF_toHostFifo_enqReq_ehrReg_0_BITS_17_TO_0___d25;
      }
      ++num;
      if ((backing.DEF_toHostFifo_enqReq_ehrReg_0_BIT_18___d11) != DEF_toHostFifo_enqReq_ehrReg_0_BIT_18___d11)
      {
	vcd_write_val(sim_hdl, num, DEF_toHostFifo_enqReq_ehrReg_0_BIT_18___d11, 1u);
	backing.DEF_toHostFifo_enqReq_ehrReg_0_BIT_18___d11 = DEF_toHostFifo_enqReq_ehrReg_0_BIT_18___d11;
      }
      ++num;
      if ((backing.DEF_toHostFifo_enqReq_ehrReg___d10) != DEF_toHostFifo_enqReq_ehrReg___d10)
      {
	vcd_write_val(sim_hdl, num, DEF_toHostFifo_enqReq_ehrReg___d10, 19u);
	backing.DEF_toHostFifo_enqReq_ehrReg___d10 = DEF_toHostFifo_enqReq_ehrReg___d10;
      }
      ++num;
      if ((backing.DEF_toHostFifo_enqReq_wires_0_wget_BIT_18___d9) != DEF_toHostFifo_enqReq_wires_0_wget_BIT_18___d9)
      {
	vcd_write_val(sim_hdl, num, DEF_toHostFifo_enqReq_wires_0_wget_BIT_18___d9, 1u);
	backing.DEF_toHostFifo_enqReq_wires_0_wget_BIT_18___d9 = DEF_toHostFifo_enqReq_wires_0_wget_BIT_18___d9;
      }
      ++num;
      if ((backing.DEF_toHostFifo_enqReq_wires_0_wget____d8) != DEF_toHostFifo_enqReq_wires_0_wget____d8)
      {
	vcd_write_val(sim_hdl, num, DEF_toHostFifo_enqReq_wires_0_wget____d8, 19u);
	backing.DEF_toHostFifo_enqReq_wires_0_wget____d8 = DEF_toHostFifo_enqReq_wires_0_wget____d8;
      }
      ++num;
      if ((backing.DEF_toHostFifo_enqReq_wires_0_whas____d7) != DEF_toHostFifo_enqReq_wires_0_whas____d7)
      {
	vcd_write_val(sim_hdl, num, DEF_toHostFifo_enqReq_wires_0_whas____d7, 1u);
	backing.DEF_toHostFifo_enqReq_wires_0_whas____d7 = DEF_toHostFifo_enqReq_wires_0_whas____d7;
      }
      ++num;
      if ((backing.DEF_toHostFifo_enqReq_wires_1_wget_BIT_18___d6) != DEF_toHostFifo_enqReq_wires_1_wget_BIT_18___d6)
      {
	vcd_write_val(sim_hdl, num, DEF_toHostFifo_enqReq_wires_1_wget_BIT_18___d6, 1u);
	backing.DEF_toHostFifo_enqReq_wires_1_wget_BIT_18___d6 = DEF_toHostFifo_enqReq_wires_1_wget_BIT_18___d6;
      }
      ++num;
      if ((backing.DEF_toHostFifo_enqReq_wires_1_wget____d5) != DEF_toHostFifo_enqReq_wires_1_wget____d5)
      {
	vcd_write_val(sim_hdl, num, DEF_toHostFifo_enqReq_wires_1_wget____d5, 19u);
	backing.DEF_toHostFifo_enqReq_wires_1_wget____d5 = DEF_toHostFifo_enqReq_wires_1_wget____d5;
      }
      ++num;
      if ((backing.DEF_toHostFifo_enqReq_wires_1_whas____d4) != DEF_toHostFifo_enqReq_wires_1_whas____d4)
      {
	vcd_write_val(sim_hdl, num, DEF_toHostFifo_enqReq_wires_1_whas____d4, 1u);
	backing.DEF_toHostFifo_enqReq_wires_1_whas____d4 = DEF_toHostFifo_enqReq_wires_1_whas____d4;
      }
      ++num;
      if ((backing.DEF_toHostFifo_full__h5764) != DEF_toHostFifo_full__h5764)
      {
	vcd_write_val(sim_hdl, num, DEF_toHostFifo_full__h5764, 1u);
	backing.DEF_toHostFifo_full__h5764 = DEF_toHostFifo_full__h5764;
      }
      ++num;
      if ((backing.DEF_x__h7622) != DEF_x__h7622)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h7622, 1u);
	backing.DEF_x__h7622 = DEF_x__h7622;
      }
      ++num;
      if ((backing.PORT_EN_cpuToHost) != PORT_EN_cpuToHost)
      {
	vcd_write_val(sim_hdl, num, PORT_EN_cpuToHost, 1u);
	backing.PORT_EN_cpuToHost = PORT_EN_cpuToHost;
      }
      ++num;
      if ((backing.PORT_EN_start) != PORT_EN_start)
      {
	vcd_write_val(sim_hdl, num, PORT_EN_start, 1u);
	backing.PORT_EN_start = PORT_EN_start;
      }
      ++num;
      if ((backing.PORT_EN_wr) != PORT_EN_wr)
      {
	vcd_write_val(sim_hdl, num, PORT_EN_wr, 1u);
	backing.PORT_EN_wr = PORT_EN_wr;
      }
      ++num;
      if ((backing.PORT_RDY_cpuToHost) != PORT_RDY_cpuToHost)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_cpuToHost, 1u);
	backing.PORT_RDY_cpuToHost = PORT_RDY_cpuToHost;
      }
      ++num;
      if ((backing.PORT_RDY_rd) != PORT_RDY_rd)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_rd, 1u);
	backing.PORT_RDY_rd = PORT_RDY_rd;
      }
      ++num;
      if ((backing.PORT_RDY_start) != PORT_RDY_start)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_start, 1u);
	backing.PORT_RDY_start = PORT_RDY_start;
      }
      ++num;
      if ((backing.PORT_RDY_started) != PORT_RDY_started)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_started, 1u);
	backing.PORT_RDY_started = PORT_RDY_started;
      }
      ++num;
      if ((backing.PORT_RDY_wr) != PORT_RDY_wr)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_wr, 1u);
	backing.PORT_RDY_wr = PORT_RDY_wr;
      }
      ++num;
      if ((backing.PORT_cpuToHost) != PORT_cpuToHost)
      {
	vcd_write_val(sim_hdl, num, PORT_cpuToHost, 18u);
	backing.PORT_cpuToHost = PORT_cpuToHost;
      }
      ++num;
      if ((backing.PORT_rd) != PORT_rd)
      {
	vcd_write_val(sim_hdl, num, PORT_rd, 32u);
	backing.PORT_rd = PORT_rd;
      }
      ++num;
      if ((backing.PORT_rd_idx) != PORT_rd_idx)
      {
	vcd_write_val(sim_hdl, num, PORT_rd_idx, 12u);
	backing.PORT_rd_idx = PORT_rd_idx;
      }
      ++num;
      if ((backing.PORT_start_id) != PORT_start_id)
      {
	vcd_write_val(sim_hdl, num, PORT_start_id, 32u);
	backing.PORT_start_id = PORT_start_id;
      }
      ++num;
      if ((backing.PORT_started) != PORT_started)
      {
	vcd_write_val(sim_hdl, num, PORT_started, 1u);
	backing.PORT_started = PORT_started;
      }
      ++num;
      if ((backing.PORT_wr_idx) != PORT_wr_idx)
      {
	vcd_write_val(sim_hdl, num, PORT_wr_idx, 13u);
	backing.PORT_wr_idx = PORT_wr_idx;
      }
      ++num;
      if ((backing.PORT_wr_val) != PORT_wr_val)
      {
	vcd_write_val(sim_hdl, num, PORT_wr_val, 32u);
	backing.PORT_wr_val = PORT_wr_val;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_count, 1u);
      backing.DEF_CAN_FIRE_RL_count = DEF_CAN_FIRE_RL_count;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_toHostFifo_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_toHostFifo_canonicalize = DEF_CAN_FIRE_RL_toHostFifo_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_toHostFifo_clearReq_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_toHostFifo_clearReq_canonicalize = DEF_CAN_FIRE_RL_toHostFifo_clearReq_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_toHostFifo_deqReq_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_toHostFifo_deqReq_canonicalize = DEF_CAN_FIRE_RL_toHostFifo_deqReq_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_toHostFifo_enqReq_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_toHostFifo_enqReq_canonicalize = DEF_CAN_FIRE_RL_toHostFifo_enqReq_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_cpuToHost, 1u);
      backing.DEF_CAN_FIRE_cpuToHost = DEF_CAN_FIRE_cpuToHost;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_rd, 1u);
      backing.DEF_CAN_FIRE_rd = DEF_CAN_FIRE_rd;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_start, 1u);
      backing.DEF_CAN_FIRE_start = DEF_CAN_FIRE_start;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_started, 1u);
      backing.DEF_CAN_FIRE_started = DEF_CAN_FIRE_started;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_wr, 1u);
      backing.DEF_CAN_FIRE_wr = DEF_CAN_FIRE_wr;
      vcd_write_val(sim_hdl, num++, DEF_IF_toHostFifo_clearReq_wires_0_whas__3_THEN_to_ETC___d46, 1u);
      backing.DEF_IF_toHostFifo_clearReq_wires_0_whas__3_THEN_to_ETC___d46 = DEF_IF_toHostFifo_clearReq_wires_0_whas__3_THEN_to_ETC___d46;
      vcd_write_val(sim_hdl, num++, DEF_IF_toHostFifo_deqReq_wires_1_whas__3_THEN_toHo_ETC___d39, 1u);
      backing.DEF_IF_toHostFifo_deqReq_wires_1_whas__3_THEN_toHo_ETC___d39 = DEF_IF_toHostFifo_deqReq_wires_1_whas__3_THEN_toHo_ETC___d39;
      vcd_write_val(sim_hdl, num++, DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_NOT_toH_ETC___d20, 1u);
      backing.DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_NOT_toH_ETC___d20 = DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_NOT_toH_ETC___d20;
      vcd_write_val(sim_hdl, num++, DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d13, 1u);
      backing.DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d13 = DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d13;
      vcd_write_val(sim_hdl, num++, DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d27, 18u);
      backing.DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d27 = DEF_IF_toHostFifo_enqReq_wires_1_whas_THEN_toHostF_ETC___d27;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_count, 1u);
      backing.DEF_WILL_FIRE_RL_count = DEF_WILL_FIRE_RL_count;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_toHostFifo_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_toHostFifo_canonicalize = DEF_WILL_FIRE_RL_toHostFifo_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_toHostFifo_clearReq_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_toHostFifo_clearReq_canonicalize = DEF_WILL_FIRE_RL_toHostFifo_clearReq_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_toHostFifo_deqReq_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_toHostFifo_deqReq_canonicalize = DEF_WILL_FIRE_RL_toHostFifo_deqReq_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_toHostFifo_enqReq_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_toHostFifo_enqReq_canonicalize = DEF_WILL_FIRE_RL_toHostFifo_enqReq_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_cpuToHost, 1u);
      backing.DEF_WILL_FIRE_cpuToHost = DEF_WILL_FIRE_cpuToHost;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_start, 1u);
      backing.DEF_WILL_FIRE_start = DEF_WILL_FIRE_start;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_wr, 1u);
      backing.DEF_WILL_FIRE_wr = DEF_WILL_FIRE_wr;
      vcd_write_val(sim_hdl, num++, DEF__read__h117, 32u);
      backing.DEF__read__h117 = DEF__read__h117;
      vcd_write_val(sim_hdl, num++, DEF__read__h169, 32u);
      backing.DEF__read__h169 = DEF__read__h169;
      vcd_write_val(sim_hdl, num++, DEF_startReg_read____d93, 1u);
      backing.DEF_startReg_read____d93 = DEF_startReg_read____d93;
      vcd_write_val(sim_hdl, num++, DEF_toHostFifo_clearReq_ehrReg___d45, 1u);
      backing.DEF_toHostFifo_clearReq_ehrReg___d45 = DEF_toHostFifo_clearReq_ehrReg___d45;
      vcd_write_val(sim_hdl, num++, DEF_toHostFifo_clearReq_wires_0_wget____d44, 1u);
      backing.DEF_toHostFifo_clearReq_wires_0_wget____d44 = DEF_toHostFifo_clearReq_wires_0_wget____d44;
      vcd_write_val(sim_hdl, num++, DEF_toHostFifo_clearReq_wires_0_whas____d43, 1u);
      backing.DEF_toHostFifo_clearReq_wires_0_whas____d43 = DEF_toHostFifo_clearReq_wires_0_whas____d43;
      vcd_write_val(sim_hdl, num++, DEF_toHostFifo_deqReq_ehrReg___d37, 1u);
      backing.DEF_toHostFifo_deqReq_ehrReg___d37 = DEF_toHostFifo_deqReq_ehrReg___d37;
      vcd_write_val(sim_hdl, num++, DEF_toHostFifo_empty__h5796, 1u);
      backing.DEF_toHostFifo_empty__h5796 = DEF_toHostFifo_empty__h5796;
      vcd_write_val(sim_hdl, num++, DEF_toHostFifo_enqReq_ehrReg_0_BITS_17_TO_0___d25, 18u);
      backing.DEF_toHostFifo_enqReq_ehrReg_0_BITS_17_TO_0___d25 = DEF_toHostFifo_enqReq_ehrReg_0_BITS_17_TO_0___d25;
      vcd_write_val(sim_hdl, num++, DEF_toHostFifo_enqReq_ehrReg_0_BIT_18___d11, 1u);
      backing.DEF_toHostFifo_enqReq_ehrReg_0_BIT_18___d11 = DEF_toHostFifo_enqReq_ehrReg_0_BIT_18___d11;
      vcd_write_val(sim_hdl, num++, DEF_toHostFifo_enqReq_ehrReg___d10, 19u);
      backing.DEF_toHostFifo_enqReq_ehrReg___d10 = DEF_toHostFifo_enqReq_ehrReg___d10;
      vcd_write_val(sim_hdl, num++, DEF_toHostFifo_enqReq_wires_0_wget_BIT_18___d9, 1u);
      backing.DEF_toHostFifo_enqReq_wires_0_wget_BIT_18___d9 = DEF_toHostFifo_enqReq_wires_0_wget_BIT_18___d9;
      vcd_write_val(sim_hdl, num++, DEF_toHostFifo_enqReq_wires_0_wget____d8, 19u);
      backing.DEF_toHostFifo_enqReq_wires_0_wget____d8 = DEF_toHostFifo_enqReq_wires_0_wget____d8;
      vcd_write_val(sim_hdl, num++, DEF_toHostFifo_enqReq_wires_0_whas____d7, 1u);
      backing.DEF_toHostFifo_enqReq_wires_0_whas____d7 = DEF_toHostFifo_enqReq_wires_0_whas____d7;
      vcd_write_val(sim_hdl, num++, DEF_toHostFifo_enqReq_wires_1_wget_BIT_18___d6, 1u);
      backing.DEF_toHostFifo_enqReq_wires_1_wget_BIT_18___d6 = DEF_toHostFifo_enqReq_wires_1_wget_BIT_18___d6;
      vcd_write_val(sim_hdl, num++, DEF_toHostFifo_enqReq_wires_1_wget____d5, 19u);
      backing.DEF_toHostFifo_enqReq_wires_1_wget____d5 = DEF_toHostFifo_enqReq_wires_1_wget____d5;
      vcd_write_val(sim_hdl, num++, DEF_toHostFifo_enqReq_wires_1_whas____d4, 1u);
      backing.DEF_toHostFifo_enqReq_wires_1_whas____d4 = DEF_toHostFifo_enqReq_wires_1_whas____d4;
      vcd_write_val(sim_hdl, num++, DEF_toHostFifo_full__h5764, 1u);
      backing.DEF_toHostFifo_full__h5764 = DEF_toHostFifo_full__h5764;
      vcd_write_val(sim_hdl, num++, DEF_x__h7622, 1u);
      backing.DEF_x__h7622 = DEF_x__h7622;
      vcd_write_val(sim_hdl, num++, PORT_EN_cpuToHost, 1u);
      backing.PORT_EN_cpuToHost = PORT_EN_cpuToHost;
      vcd_write_val(sim_hdl, num++, PORT_EN_start, 1u);
      backing.PORT_EN_start = PORT_EN_start;
      vcd_write_val(sim_hdl, num++, PORT_EN_wr, 1u);
      backing.PORT_EN_wr = PORT_EN_wr;
      vcd_write_val(sim_hdl, num++, PORT_RDY_cpuToHost, 1u);
      backing.PORT_RDY_cpuToHost = PORT_RDY_cpuToHost;
      vcd_write_val(sim_hdl, num++, PORT_RDY_rd, 1u);
      backing.PORT_RDY_rd = PORT_RDY_rd;
      vcd_write_val(sim_hdl, num++, PORT_RDY_start, 1u);
      backing.PORT_RDY_start = PORT_RDY_start;
      vcd_write_val(sim_hdl, num++, PORT_RDY_started, 1u);
      backing.PORT_RDY_started = PORT_RDY_started;
      vcd_write_val(sim_hdl, num++, PORT_RDY_wr, 1u);
      backing.PORT_RDY_wr = PORT_RDY_wr;
      vcd_write_val(sim_hdl, num++, PORT_cpuToHost, 18u);
      backing.PORT_cpuToHost = PORT_cpuToHost;
      vcd_write_val(sim_hdl, num++, PORT_rd, 32u);
      backing.PORT_rd = PORT_rd;
      vcd_write_val(sim_hdl, num++, PORT_rd_idx, 12u);
      backing.PORT_rd_idx = PORT_rd_idx;
      vcd_write_val(sim_hdl, num++, PORT_start_id, 32u);
      backing.PORT_start_id = PORT_start_id;
      vcd_write_val(sim_hdl, num++, PORT_started, 1u);
      backing.PORT_started = PORT_started;
      vcd_write_val(sim_hdl, num++, PORT_wr_idx, 13u);
      backing.PORT_wr_idx = PORT_wr_idx;
      vcd_write_val(sim_hdl, num++, PORT_wr_val, 32u);
      backing.PORT_wr_val = PORT_wr_val;
    }
}

void MOD_mkCsrFile::vcd_prims(tVCDDumpType dt, MOD_mkCsrFile &backing)
{
  INST_coreId.dump_VCD(dt, backing.INST_coreId);
  INST_cycles.dump_VCD(dt, backing.INST_cycles);
  INST_numInsts.dump_VCD(dt, backing.INST_numInsts);
  INST_startReg.dump_VCD(dt, backing.INST_startReg);
  INST_toHostFifo_clearReq_ehrReg.dump_VCD(dt, backing.INST_toHostFifo_clearReq_ehrReg);
  INST_toHostFifo_clearReq_ignored_wires_0.dump_VCD(dt,
						    backing.INST_toHostFifo_clearReq_ignored_wires_0);
  INST_toHostFifo_clearReq_ignored_wires_1.dump_VCD(dt,
						    backing.INST_toHostFifo_clearReq_ignored_wires_1);
  INST_toHostFifo_clearReq_virtual_reg_0.dump_VCD(dt, backing.INST_toHostFifo_clearReq_virtual_reg_0);
  INST_toHostFifo_clearReq_virtual_reg_1.dump_VCD(dt, backing.INST_toHostFifo_clearReq_virtual_reg_1);
  INST_toHostFifo_clearReq_wires_0.dump_VCD(dt, backing.INST_toHostFifo_clearReq_wires_0);
  INST_toHostFifo_clearReq_wires_1.dump_VCD(dt, backing.INST_toHostFifo_clearReq_wires_1);
  INST_toHostFifo_data_0.dump_VCD(dt, backing.INST_toHostFifo_data_0);
  INST_toHostFifo_data_1.dump_VCD(dt, backing.INST_toHostFifo_data_1);
  INST_toHostFifo_deqP.dump_VCD(dt, backing.INST_toHostFifo_deqP);
  INST_toHostFifo_deqReq_ehrReg.dump_VCD(dt, backing.INST_toHostFifo_deqReq_ehrReg);
  INST_toHostFifo_deqReq_ignored_wires_0.dump_VCD(dt, backing.INST_toHostFifo_deqReq_ignored_wires_0);
  INST_toHostFifo_deqReq_ignored_wires_1.dump_VCD(dt, backing.INST_toHostFifo_deqReq_ignored_wires_1);
  INST_toHostFifo_deqReq_ignored_wires_2.dump_VCD(dt, backing.INST_toHostFifo_deqReq_ignored_wires_2);
  INST_toHostFifo_deqReq_virtual_reg_0.dump_VCD(dt, backing.INST_toHostFifo_deqReq_virtual_reg_0);
  INST_toHostFifo_deqReq_virtual_reg_1.dump_VCD(dt, backing.INST_toHostFifo_deqReq_virtual_reg_1);
  INST_toHostFifo_deqReq_virtual_reg_2.dump_VCD(dt, backing.INST_toHostFifo_deqReq_virtual_reg_2);
  INST_toHostFifo_deqReq_wires_0.dump_VCD(dt, backing.INST_toHostFifo_deqReq_wires_0);
  INST_toHostFifo_deqReq_wires_1.dump_VCD(dt, backing.INST_toHostFifo_deqReq_wires_1);
  INST_toHostFifo_deqReq_wires_2.dump_VCD(dt, backing.INST_toHostFifo_deqReq_wires_2);
  INST_toHostFifo_empty.dump_VCD(dt, backing.INST_toHostFifo_empty);
  INST_toHostFifo_enqP.dump_VCD(dt, backing.INST_toHostFifo_enqP);
  INST_toHostFifo_enqReq_ehrReg.dump_VCD(dt, backing.INST_toHostFifo_enqReq_ehrReg);
  INST_toHostFifo_enqReq_ignored_wires_0.dump_VCD(dt, backing.INST_toHostFifo_enqReq_ignored_wires_0);
  INST_toHostFifo_enqReq_ignored_wires_1.dump_VCD(dt, backing.INST_toHostFifo_enqReq_ignored_wires_1);
  INST_toHostFifo_enqReq_ignored_wires_2.dump_VCD(dt, backing.INST_toHostFifo_enqReq_ignored_wires_2);
  INST_toHostFifo_enqReq_virtual_reg_0.dump_VCD(dt, backing.INST_toHostFifo_enqReq_virtual_reg_0);
  INST_toHostFifo_enqReq_virtual_reg_1.dump_VCD(dt, backing.INST_toHostFifo_enqReq_virtual_reg_1);
  INST_toHostFifo_enqReq_virtual_reg_2.dump_VCD(dt, backing.INST_toHostFifo_enqReq_virtual_reg_2);
  INST_toHostFifo_enqReq_wires_0.dump_VCD(dt, backing.INST_toHostFifo_enqReq_wires_0);
  INST_toHostFifo_enqReq_wires_1.dump_VCD(dt, backing.INST_toHostFifo_enqReq_wires_1);
  INST_toHostFifo_enqReq_wires_2.dump_VCD(dt, backing.INST_toHostFifo_enqReq_wires_2);
  INST_toHostFifo_full.dump_VCD(dt, backing.INST_toHostFifo_full);
}
