/*
 * Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
 * 
 * On Sat Mar 12 13:28:57 EST 2016
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkDutWrapper_h__
#define __mkDutWrapper_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkProc.h"


/* Class declaration for the mkDutWrapper module */
class MOD_mkDutWrapper : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkProc INST_m;
 
 /* Constructor */
 public:
  MOD_mkDutWrapper(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUInt8 PORT_EN_cpuToHost;
  tUInt8 PORT_EN_hostToCpu;
  tUInt8 PORT_EN_memInit_request_put;
  tUInt8 PORT_EN_ddr3client_request_get;
  tUInt8 PORT_EN_ddr3client_response_put;
  tUInt32 PORT_hostToCpu_startpc;
  tUWide PORT_memInit_request_put;
  tUWide PORT_ddr3client_response_put;
  tUInt32 PORT_cpuToHost;
  tUInt8 PORT_RDY_cpuToHost;
  tUInt8 PORT_RDY_hostToCpu;
  tUInt8 PORT_RDY_memInit_request_put;
  tUInt8 PORT_memInit_done;
  tUInt8 PORT_RDY_memInit_done;
  tUWide PORT_ddr3client_request_get;
  tUInt8 PORT_RDY_ddr3client_request_get;
  tUInt8 PORT_RDY_ddr3client_response_put;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_ddr3client_response_put;
  tUInt8 DEF_WILL_FIRE_ddr3client_request_get;
  tUInt8 DEF_WILL_FIRE_memInit_request_put;
  tUInt8 DEF_WILL_FIRE_hostToCpu;
  tUInt8 DEF_WILL_FIRE_cpuToHost;
  tUInt8 DEF_CAN_FIRE_ddr3client_response_put;
  tUInt8 DEF_CAN_FIRE_ddr3client_request_get;
  tUInt8 DEF_CAN_FIRE_memInit_done;
  tUInt8 DEF_CAN_FIRE_memInit_request_put;
  tUInt8 DEF_CAN_FIRE_hostToCpu;
  tUInt8 DEF_CAN_FIRE_cpuToHost;
 
 /* Local definitions */
 private:
  tUWide DEF_memInit_request_put_BITS_535_TO_0___d2;
  tUWide DEF_IF_memInit_request_put_BIT_536_THEN_DONTCARE_E_ETC___d3;
  tUWide DEF_memInit_request_put_BIT_536_CONCAT_IF_memInit__ETC___d4;
 
 /* Rules */
 public:
 
 /* Methods */
 public:
  tUInt32 METH_cpuToHost();
  tUInt8 METH_RDY_cpuToHost();
  void METH_hostToCpu(tUInt32 ARG_hostToCpu_startpc);
  tUInt8 METH_RDY_hostToCpu();
  void METH_memInit_request_put(tUWide ARG_memInit_request_put);
  tUInt8 METH_RDY_memInit_request_put();
  tUInt8 METH_memInit_done();
  tUInt8 METH_RDY_memInit_done();
  tUWide METH_ddr3client_request_get();
  tUInt8 METH_RDY_ddr3client_request_get();
  void METH_ddr3client_response_put(tUWide ARG_ddr3client_response_put);
  tUInt8 METH_RDY_ddr3client_response_put();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkDutWrapper &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkDutWrapper &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkDutWrapper &backing);
};

#endif /* ifndef __mkDutWrapper_h__ */
